baseURL = "https://fachschaftbioinformatik-ffm.de/"
title = "Fachschaft Bioinformatik @GU"
author = "Fachschaft Bioinformatik"
copyright = "Fachschaft Bioinformatik"
languageCode = "en"
theme = "tailwind"

[params]
  # dir name of your blog content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"
  subtitle = "Bioinformatics student council"
  description = "Bioinformatics student council at Goethe University Frankfurt"
  keywords = "bioinformatics, student council, Goethe University Frankfurt"

  [params.header]
    logo = "logo_simple.svg"

  [params.footer]
    since = 2013
    poweredby = false

[menu]

  [[menu.main]]
    identifier = "post"
    name = "Updates"
    pageRef = "/posts"
    weight = 1

  [[menu.main]]
    identifier = "calendar"
    name = "Calendar"
    pageRef = "/calendar"
    weight = 2

  [[menu.main]]
    identifier = "resources"
    name = "Resources for students"
    pageRef = "/resources"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "About us"
    pageRef = "/about"
    weight = 4

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup.goldmark.renderer]
      unsafe = true

[pagination]
  perPage = 10